# Article 2 {#Article2}

Evans, R., Lyons, M., Brewer, G., & Tucci, S. (2019). The purrfect match: The influence of personality on owner satisfaction with their domestic cat (Felis silvestris catus). Personality and Individual Differences, 138, 252–256.

Factual
One of…?
How many participants were there? 
How were participants recruited? 
Was there an equal number of males and females? 

How many scales did participants fill out about themselves? 
Was the Dark Triad correlated with cat dominance? If it was, was it positive or negative? If significant, at what probability level? 
Discussion
The researchers required participants to have selected the cats themselves. Would you expect the results to be different if the cats had not been selected by their owners?
The researchers provided no information about the reliability or validity of the measures they used. Does that concern you? Why / why not?
What might have participants interpreted the item “How satisfied are you with your cat?”
The researchers suggested that self-report items may be problematic. If you were redesigning the research, how would you deal with that issue?
How would you change this research to look at a different type of pet? (e.g., fish)
