---
title: "Understanding Research"
author: "Branch, Grosofsky, & Wagge"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/understanding_research
description: "XXX."
---

# Introduction

## Preface: For Students

-make the point that we don't expect students will understand everything they read

-resources for knowing how to read journal articles

-different types of journals with different audiences

-google things you don't understand 

-try to figure out when something is worth trying to understand (e.g. technical details sometimes don't need to be figured through if that's not what you need to get from the paper)

\
\

## Preface: For Instructors

### General introduction

As with Andrea Milinki's A Cross Section of Psychological Research, we have put together a collection of empirical psychological research suitable for students learning about research methods and statistics. By reading empirical articles they are able to see applications of the techniques they are learning about in the "real world" of published research. These articles could also be used for students in other classes as we sought to include articles that would both be interesting and understandable to students.

### Article selection

We sought articles that represented a wide range of subfields in psychology as well as a diverse range of statistical and methodological techniques.
